attendance_logger/urls.py
from django.urls import path
from .views import base,register,Login,home,history,request_leave

app_name = "attendance_logger"

urlpatterns = [
    path('register/',register,name="register"),
    path('login/',Login,name="login"),
    path('base/',base,name="base"),
    path('home/',home,name="home"),
    path('history/',history,name="history"),
    path("request/",request_leave,name="request"),
]

attendance_system/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('log/',include('attendance_logger.urls')),
]

attendance_logger/models.py
from django.db import models

# Create your models here.

def get_choices():
    choices = {("U","Unmarked"),("P","Present"),("V","Vacation"),("L","Late"),("S","Sick")}
    return choices

class AttendanceRecord(models.Model):
    employee_name = models.CharField(max_length=50)
    employee_id = models.CharField(max_length=10)
    date = models.DateField()
    attendance_status = models.CharField(max_length=1,choices=get_choices(),default="P")

    def __str__(self):
        return self.employee_name
    
    def get_status_for_date(self):
        data = AttendanceRecord.objects.get(employee_id=self.employee_id,date=self.date).attendance_status
        return data

attendance_logger/forms.py
from django.contrib.auth.models import User

class Usercreation():
    class Meta:
        model = User
        fields = ["username","email","password1","password2"]

attendance_logger/views.py
from django.shortcuts import render,redirect
from .models import AttendanceRecord
import datetime
from collections import defaultdict
from .forms import Usercreation
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate,login
from django.contrib.auth.decorators import login_required

# Create your views here.

def register(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            return redirect("attendance_logger:home")   

        else:
            return render(request=request,template_name="register.html",context={"error":form.errors})
        
    else:
        form = UserCreationForm()
        context = {
            "form":form,
        }
    return render(request=request,template_name="register.html",context=context)

def Login(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request,username=username,password=password)
        if user is not None:
            form = login(request,user)
            return redirect("attendance_logger:home")
            
        
    return render(request=request,template_name="login.html")

@login_required
def base(request):
    return render(request=request,template_name="base.html")


@login_required
def home(request):
    today = datetime.date.today()
    lower_range,upper_range = today - datetime.timedelta(days=5),today + datetime.timedelta(days=5)
    date_list = []
    start_date = lower_range
    while start_date <= upper_range:
        date_list.append({"day":start_date.strftime('%A'),"date":start_date.strftime('%d/%m/%Y')})
        start_date += datetime.timedelta(days=1)
    data = AttendanceRecord.objects.filter(date__lte=upper_range,date__gte=lower_range).values()
    names = AttendanceRecord.objects.filter(date__lte=upper_range,date__gte=lower_range).values("employee_name").distinct()
    data_dict = defaultdict(list)
    for record in data:
        data_dict[record['employee_name']].append({"status":record["attendance_status"],"date":record["date"].strftime('%d/%m/%Y')})
    options = [
        {'value':'U','label':'Unmarked'},
        {'value':'P','label':'Present'},
        {'value':'V','label':'Vacation'},
        {'value':'S','label':'Sick'},
        {'value':'L','label':'Late'}
    ]
    print("------------------",data_dict)
    print("------------------",names)
    return  render(request=request,template_name="homepage3.html",context={"data_dict":data_dict, "date_tuple":date_list,"options":options,"names":names})

@login_required
def history(request):
    data = [
        {'x':10,'y':20,'value':5},
        {'x':30,'y':40,'value':10}
    ]
    return render(request=request,template_name="history.html",context={"data":data})

def request_leave(request):
    return render(request=request,template_name="request.html")

attendance_logger/templates/base.html
<html>
<head>
  {% load static %}
  {% load bootstrap5 %}
  {% bootstrap_css %}
  {% bootstrap_javascript %}
  
  {% block head %}
  {% endblock head %}

</head>


<body >

    <div class="container-fluid"  style="height:50px;">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 link-body-emphasis text-decoration-none">
          {% comment %} <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"></use></svg> {% endcomment %}
          <img src="{% static 'logo' %}" height="32" width="32">
        </a>

        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
          <li><a href="#" class="nav-link px-2 link-secondary">APP NAME</a></li>
          <li><a href="#" class="nav-link px-2 link-body-emphasis">Check-In</a></li>
          <li><a href="#" class="nav-link px-2 link-body-emphasis">History</a></li>
          <li><a href="#" class="nav-link px-2 link-body-emphasis">Request Leave</a></li>
          <li><a href="#" class="nav-link px-2 link-body-emphasis">Teams</a></li>
        </ul>

        {% comment %} <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" role="search">
          <input type="search" class="form-control" placeholder="Search..." aria-label="Search">
        </form> {% endcomment %}

        <div class="dropdown text-end">
          <a href="#" class="d-block link-body-emphasis text-decoration-none dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
            <img src="{% static 'empty_profile.png' %}" alt="mdo" width="32" height="32" class="rounded-circle">
          </a>
          <ul class="dropdown-menu text-small">
            <li><a class="dropdown-item" href="#">View Status</a></li>
            <li><a class="dropdown-item" href="#">Settings</a></li>
            <li><a class="dropdown-item" href="#">Profile</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Sign out</a></li>
          </ul>
        </div>
      </div>
    </div>
  

{% block styles%}
{% endblock %}

{% block content %}

  {% endblock %}
  
<div class="container-fluid">
  <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
    <p class="col-md-4 mb-0 text-body-secondary" style="color:white;">© 2024 Company, Inc</p>

    <a href="/" class="col-md-4 d-flex align-items-center justify-content-center mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none">
      <img src="{% static 'logo' %}" alt="mdo" width="32" height="32" >
    </a>

    <ul class="nav col-md-4 justify-content-end">
      <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Check-In</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">History</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Request Leave</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Teams</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">About</a></li>
    </ul>
  </footer>
</div>

{% block scriptjs %}
{% endblock scriptjs %}

</body>

attendance_logger/templates/checkin.html
{% extends 'base.html' %}
{%  load static %}

{% block styles%}
<style>
    .checkin-main{
        height:70vh;
        display:flex;
        flex-direction:column;
        gap:50px;
    }
    .checkin-main *{
        color:white;
    } 
    .info{
        display:flex;
        gap:300px;
    }
    .buttons{
        margin-top:100px;
    }

</style>
{% endblock %}

{% block content %}
<div class="px-4 py-5 my-5 text-center checkin-main">
    <img class="d-block mx-auto mb-4" src="{% static 'logo.png' %}" alt="" width="72" height="57">
    <h1 class="display-5 fw-bold text-body-emphasis">Mark Your Attendance</h1>
    <div class="col-lg-6 mx-auto main">
    <div class="info">
    <div >
      <p class="lead mb-4">NAME:{{data.name}}</p>
      <p class="lead mb-4">DATE:{{ today|date:"Y-m-d"}}</p>
      </div>
      <div >
      <p class="lead mb-4">TIME:{{data.time}}</p>
      <p class="lead mb-4">STATUS:{{data.status}}</p>
        </div>
        </div>
      <div class="d-grid gap-2 d-sm-flex justify-content-sm-center buttons">
        <button type="button" class="btn btn-primary btn-lg px-4 gap-3">Mark Your Attendance</button>
        <button type="button" class="btn btn-outline-secondary btn-lg px-4">Request A Leave</button>
      </div>
    </div>
  </div>
{% endblock content %}

attendance_logger/templates/history.html
{% comment %} {% extends 'base.html' %} {% endcomment %}
{%  load static %}

{% block head %}
<script src="https://d3js.org/d3.v4.js"></script>
<script src="https://d3js.org/d3-scale-chromatic.v1.min.js"></script>
{% load static %}
{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}

{% endblock head %}

{% block styles%}
<style>
    .main-page{
        display: grid;
        grid-template-columns: 2fr 10fr;
    }
    .sidebar-main{
        height:100vh;
    }
    .page-content{
      display: flex;
      flex-direction: column;
      gap: 50px;
      margin: 30px 50px ;
      color: black;
    }
    .top-header{
      display: flex;
      justify-content: space-between;
    }
    .name-and-icon{
      display: flex;
      align-items: center;
      gap: 20px;
    }

</style>
{% endblock styles %}

{% block content %}
<div class="main-page">
  <div class="d-flex flex-column flex-shrink-0 p-3 text-bg-dark bg-dark sidebar-main" >
    <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-white text-decoration-none name-and-icon">
      <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-person-circle" viewBox="0 0 16 16">
        <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0"/>
        <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8m8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1"/>
      </svg>

      <span class="fs-4">Attendance manager</span>
    </a>
    <hr>
    <ul class="nav nav-pills flex-column mb-auto">
      <li class="nav-item">
        <a href="{% url 'attendance_logger:home' %}" class="nav-link" aria-current="page">
          <svg class="bi pe-none me-2" width="16" height="16"><use xlink:href="#home"></use></svg>
          Home
        </a>
      </li>
      <li>
        <a href="#" class="nav-link active text-white">
          <svg class="bi pe-none me-2" width="16" height="16"><use xlink:href="#speedometer2"></use></svg>
          Dashboard
        </a>
      </li>
    </ul>
    <hr>
    <!-- <div class="dropdown">
      <a href="#" class="d-flex align-items-center text-white text-decoration-none dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
        <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-person-circle" viewBox="0 0 16 16">
          <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0"/>
          <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8m8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1"/>
        </svg>
      </a>
      <ul class="dropdown-menu dropdown-menu-dark text-small shadow">
        <li><a class="dropdown-item" href="#">Sign out</a></li>
      </ul>
    </div> -->
  </div>
<div class="page-content">
  <div class="top-header">
    <h1>The main heading!</h1>
    <div class="name-and-icon">
      <p>PERSON NAME</p>
      <div class="dropdown">
        <a href="#" class="d-flex align-items-center text-decoration-none dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
          <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="black" class="bi bi-person-circle" viewBox="0 0 16 16">
            <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0"/>
            <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8m8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1"/>
          </svg>
        </a>
        <ul class="dropdown-menu dropdown-menu-dark text-small shadow">
          <li><a class="dropdown-item" href="#">Sign out</a></li>
        </ul>
      </div>
    </div>
  </div>
<div class="px-4 py-5 my-5 text-center checkin-main">
    <!-- <img class="d-block mx-auto mb-4" src="{% static 'logo.png' %}" alt="" width="72" height="57"> -->
    <h1 class="display-5 fw-bold text-body-emphasis">Your Attendance History</h1>
    <div class="col-lg-6 mx-auto main">
    <div id="cal-heatmap"></div>
</div>
{% endblock content %}

{% block scriptjs %}
<script>
import {Calendar} from "@d3/calendar"
console.log("works");
</script>
{% endblock scriptjs %}

attendance_logger/templates/homepage3.html
<head>
    {% load static %}
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
</head>
<body>
    <style>
    .main-page{
        display: grid;
        grid-template-columns: 2fr 10fr;
    }
    .sidebar-main{
        height:100vh;
    }
    .page-content{
      display: flex;
      flex-direction: column;
      gap: 50px;
      margin: 30px 50px ;
      color: black;
    }
    .top-header{
      display: flex;
      justify-content: space-between;
    }
    .name-and-icon{
      display: flex;
      align-items: center;
      gap: 20px;
    }
    .table-main{
        display: flex;
        flex-direction: column;
        /* gap: 10px; */
        width: 100%;
    }
    .month{
        display: grid;
        grid-template-columns: repeat(3,auto);
        background-color: white;
        /* color:white;  */
        font-size: 2rem;
        justify-items: center;
        font-weight: bolder;
        margin-bottom: 20px;
    }
    /* .month *{
        border: 2px solid black;
    } */
    button{
        background-color: white;
        border: 0;
        height: 100%;
        width: 100%;
    }
    .table-head{
        display: grid;
        grid-template-columns: repeat(12,1fr);
        background-color: black;
        color:white; 
        font-weight: bolder;
        border: 1px solid black;
        /* align-content: center; */
        /* justify-content: center; */
        justify-items: center;
        /* align-items: center; */
        width: 100%;
    }
    .row{
        margin-left: 2px;
        margin-right:2px;
        display: grid;
        grid-template-columns: repeat(12,1fr);
        grid-template-rows: 50px;
        align-items: center;
        justify-items: center;
        border-bottom: 1px solid black;
        height: 50px;
        /* width: 100%; */

    }
    
    .table-head .today{
        color: greenyellow;
    }
    .entry .dropdown>button{
      background-color: whitesmoke;
      color: black;
    }
    </style>
    <div class="main-page">
        <div class="d-flex flex-column flex-shrink-0 p-3 text-bg-dark bg-dark sidebar-main" >
            <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-white text-decoration-none name-and-icon">
              <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-person-circle" viewBox="0 0 16 16">
                <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0"/>
                <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8m8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1"/>
              </svg>

              <span class="fs-4">Attendance manager</span>
            </a>
            <hr>
            <ul class="nav nav-pills flex-column mb-auto">
              <li class="nav-item">
                <a href="#" class="nav-link active" aria-current="page">
                  <svg class="bi pe-none me-2" width="16" height="16"><use xlink:href="#home"></use></svg>
                  Home
                </a>
              </li>
              <li>
                <a href="{% url 'attendance_logger:history' %}" class="nav-link text-white">
                  <svg class="bi pe-none me-2" width="16" height="16"><use xlink:href="#speedometer2"></use></svg>
                  Dashboard
                </a>
              </li>
            </ul>
            <hr>
          </div>
        <div class="page-content">
          <div class="top-header">
            <h1>The main heading!</h1>
            <div class="name-and-icon">
              <p>PERSON NAME</p>
              <div class="dropdown">
                <a href="#" class="d-flex align-items-center text-decoration-none dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                  <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="black" class="bi bi-person-circle" viewBox="0 0 16 16">
                    <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0"/>
                    <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8m8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1"/>
                  </svg>
                </a>
                <ul class="dropdown-menu dropdown-menu-dark text-small shadow">
                  <li><a class="dropdown-item" href="#">Sign out</a></li>
                </ul>
              </div>
            </div>
          </div>
          <div class="table-main">
            <div class="month">
                <button>
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-caret-left-square-fill" viewBox="0 0 16 16">
                        <path d="M0 2a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2zm10.5 10V4a.5.5 0 0 0-.832-.374l-4.5 4a.5.5 0 0 0 0 .748l4.5 4A.5.5 0 0 0 10.5 12"/>
                      </svg>
                </button>
                <p>MAY 2024</p>
                <button>
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-caret-right-square-fill" viewBox="0 0 16 16">
                        <path d="M0 2a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2zm5.5 10a.5.5 0 0 0 .832.374l4.5-4a.5.5 0 0 0 0-.748l-4.5-4A.5.5 0 0 0 5.5 4z"/>
                      </svg>
                </button>
            </div>
            <div class="table-head">
            <div>Employee<br>Name</div>
            {% for date in date_tuple %}
            <div>{{date.day}}<br>{{date.date}}</div>
            {% endfor %}
            {% comment %} 
            <div>Wednesday<br>15</div>
            <div>Thursday<br>16</div>
            <div>Friday<br>17</div>
            <div>Saturday<br>18</div>
            <div>Sunday<br>19</div>
            <div class="today">Monday<br>20</div>
            <div>Tuesday<br>21</div>
            <div>Wednesday<br>22</div>
            <div>Thursday<br>23</div>
            <div>Friday <br>24</div> {% endcomment %}
            {% comment %} <div>Saturday<br>25</div> {% endcomment %}
              </div>        
            <div class="table-data">
            {% comment %} <h1>{{data_dict}}</h1> {% endcomment %}
            {% for name in data_dict %}
            <h1>{{name}}</h1>
                <div class="row">
                    {% comment %} <div class="entry name">{{name}}</div> {% endcomment %}
                    {% comment %} {% for date in date_tuple %} {% endcomment %}
                    {% comment %} {% if entry.date == date %} {% endcomment %}
                    <div class="entry">
                    {% comment %} <p>{{values}}</p> {% endcomment %}
                      {% comment %} <select class="form-select" onchange="changecolor(this)" aria-label="Default select example">
                        <option >Select</option>
                        {% if entry.status == 'P' %}
                        <option value="present" selected>Present</option>
                        {% else %}
                        <option value="present" >Present</option>
                        {% endif %}

                        {% if entry.status == 'L' %}
                        <option value="late" selected >Late</option>
                        {% else %}
                        <option value="late">Late</option>
                        {% endif %}

                        {% if entry.status == 'S' %}
                        <option value="sick" selected >Sick</option>
                        {% else %}
                        <option value="sick">Sick</option>
                        {% endif %}

                        {% if entry.status == 'V' %}
                        <option value="vacation" selected>Vacation</option>
                        {% else %}
                        <option value="vacation">Vacation</option>
                        {% endif %}
                      </select> {% endcomment %}
                    </div>
                    {% comment %} {% endif %} {% endcomment %}
                    {% comment %} {% endfor %} {% endcomment %}
                </div>
                {% endfor %}

            </div>
      
    </div>
    <script>

      function changecolor(item){
        var val = item.value;
            if(val=="present"){
              item.style="background-color:green;color:white;";
            }
            else if(val=="late"){
              item.style="background-color:red;color:white;";
            }
            else if(val=="vacation"){
              item.style="background-color:5AB2FF;color:black;";
            }
            else if(val=="sick"){
              item.style="background-color:yellow;color:black;";
            }
          }
      

        document.addEventListener("DOMContentLoaded",function(){
          var dropdownlist = document.querySelectorAll(".form-select");
          console.log(dropdownlist);

          dropdownlist.forEach((item)=>{
            // console.log(item.value);
            // item.addEventListener('change',changecolor);
            changecolor(item);

          })

        });
    </script>
</body>

attendance_logger/templates/login.html
<html>
<head>
  {% load static %}
  {% load bootstrap5 %}
  {% bootstrap_css %}
  {% bootstrap_javascript %}
{% block styles%}
<style>
body{
    background-color: white;
}

h1,.form-check-label{
  color: white;
}

.center{
    position:absolute;
    top:25%;
    left:45%;
}

.form-floating::placeholder {
    color:black;
    opacity:1;
}

form {
    display:flex;
    flex-direction:column;
}
</style>
{% endblock %}

</head>

<body class="d-flex align-items-center py-4 bg-body-tertiary bg-dark">
<div class="center">
<main class="form-signin w-100 m-auto">
  <form method="post">
    {% csrf_token %}
    <img class="mb-4" src="{% static 'logo.png' %}" alt="" width="72" height="57">
    <h1 class="h3 mb-3 fw-normal">Please sign in</h1>

    <div class="form-floating">
      <input type="text" class="form-control" id="floatingInput" placeholder="name@example.com" name="username">
      <label for="floatingInput">Username</label>
    </div>
    <div class="form-floating">
      <input type="password" class="form-control" id="floatingPassword" placeholder="Password" name="password">
      <label for="floatingPassword">Password</label>
    </div>

    <div class="form-check text-start my-3">
      <input class="form-check-input" type="checkbox" value="remember-me" id="flexCheckDefault">
      <label class="form-check-label" for="flexCheckDefault">
        Remember me
      </label>
    </div>
    <button class="btn btn-primary w-100 py-2" type="submit">Sign in</button>
    <p class="mt-5 mb-3 text-body-secondary">© 2017–2024</p>
  </form>
</main>
</div>
<script src="/docs/5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>

attendance_logger/templates/register.html
<html>
<head>
  {% load static %}
  {% load bootstrap5 %}
  {% bootstrap_css %}
  {% bootstrap_javascript %}
{% block styles%}
<style>

h1,.form-check-label{
  color:white;
}
.center{
    position:absolute;
    top:25%;
    left:45%;
}

.form-floating::placeholder {
    color:black;
    opacity:1;
}

form {
    display:flex;
    flex-direction:column;
}

</style>
{% endblock %}

</head>

<body class="d-flex align-items-center py-4 bg-body-tertiary bg-dark">
<div class="center">
<main class="form-signin w-100 m-auto">
  <form method="post">
  {% csrf_token %}
    <img class="mb-4" src="{% static 'logo.png' %}" alt="" width="72" height="57">
    <h1 class="h3 mb-3 fw-normal">Register</h1>

    <div class="form-floating">
      <input type="text" class="form-control" id="floatingInput" placeholder="Full Name" name="username">
      <label for="floatingInput">UserName</label>
    </div>
    <div class="form-floating">
      <input type="email" class="form-control" id="floatingInput" placeholder="name@example.com" name="email">
      <label for="floatingInput">Email address</label>
    </div>
    <div class="form-floating">
      <input type="password" class="form-control" id="floatingPassword" placeholder="Password" name="password1">
      <label for="floatingPassword">Password</label>
    </div>
    <div class="form-floating">
      <input type="password" class="form-control" id="floatingPassword" placeholder="Password" name="password2">
      <label for="floatingPassword">Confirm Password</label>
    </div>

    <div class="form-check text-start my-3">
      <input class="form-check-input" type="checkbox" value="remember-me" id="flexCheckDefault">
      <label class="form-check-label" for="flexCheckDefault">
        Remember me
      </label>
    </div>
    <button class="btn btn-primary w-100 py-2" type="submit">Register</button>
    <p class="mt-5 mb-3 text-body-secondary">© 2017–2024</p>
  </form>
</main>
</div>
<script src="/docs/5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
{{error}}
</body>